import { Handout } from "@/types/handouts/handouts";

export const handouts: Handout[] = [
  {
    id: 1,
    extension: "PPTX",
    title: "React Hook과 상태 관리 완벽 가이드",
    date: "2025.08.01",
    author: "김태현",
  },
  {
    id: 2,
    extension: "PDF",
    title: "JavaScript ES6+ 문법과 모던 개발 패턴",
    date: "2025.07.30",
    author: "박지민",
  },
  {
    id: 3,
    extension: "DOCX",
    title: "TypeScript 기초부터 고급 타입까지",
    date: "2025.07.28",
    author: "이상민",
  },
  {
    id: 4,
    extension: "PPTX",
    title: "Next.js 13 App Router 심화 학습",
    date: "2025.07.27",
    author: "최윤서",
  },
  {
    id: 5,
    extension: "XLSX",
    title: "프론트엔드 성능 최적화 체크리스트",
    date: "2025.07.25",
    author: "정현우",
  },
  {
    id: 6,
    extension: "HWP",
    title: "웹 접근성과 시맨틱 HTML 작성법",
    date: "2025.07.24",
    author: "김영희",
  },
  {
    id: 7,
    extension: "PDF",
    title: "CSS Grid와 Flexbox 레이아웃 마스터",
    date: "2025.07.22",
    author: "송민준",
  },
  {
    id: 8,
    extension: "PPTX",
    title: "RESTful API 설계 원칙과 Best Practice",
    date: "2025.07.20",
    author: "송준호",
  },
  {
    id: 9,
    extension: "DOCX",
    title: "Git 브랜치 전략과 협업 워크플로우",
    date: "2025.07.18",
    author: "오지현",
  },
  {
    id: 10,
    extension: "PDF",
    title: "데이터베이스 정규화와 인덱스 최적화",
    date: "2025.07.16",
    author: "임수진",
  },
  {
    id: 11,
    extension: "XLSX",
    title: "웹 보안 취약점 분석 및 대응 방안",
    date: "2025.07.14",
    author: "한지민",
  },
  {
    id: 12,
    extension: "HWP",
    title: "Node.js와 Express 서버 개발 가이드",
    date: "2025.07.12",
    author: "윤서연",
  },
  {
    id: 13,
    extension: "PPTX",
    title: "Docker 컨테이너와 배포 자동화",
    date: "2025.07.10",
    author: "강도현",
  },
  {
    id: 14,
    extension: "PDF",
    title: "알고리즘과 자료구조 핵심 정리",
    date: "2025.07.08",
    author: "조예린",
  },
  {
    id: 15,
    extension: "DOCX",
    title: "테스트 주도 개발(TDD) 실전 가이드",
    date: "2025.07.06",
    author: "이준혁",
  },
  {
    id: 16,
    extension: "XLSX",
    title: "프로젝트 관리와 애자일 방법론",
    date: "2025.07.04",
    author: "김소영",
  },
  {
    id: 17,
    extension: "HWP",
    title: "클린 코드 작성법과 리팩토링 기법",
    date: "2025.07.02",
    author: "박재호",
  },
  {
    id: 18,
    extension: "PDF",
    title: "GraphQL과 Apollo Client 활용법",
    date: "2025.06.30",
    author: "정민아",
  },
];
